name: Baixar Icones da Inclusao
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Transferir PNGs Coloridos
        run: |
          curl -s -L "https://img.icons8.com/color/192/jigsaw-puzzle.png" -o icon-192.png
          curl -s -L "https://img.icons8.com/color/512/jigsaw-puzzle.png" -o icon-512.png
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add icon-192.png icon-512.png
          git commit -m "Adiciona icones da inclusao coloridos" || exit 0
          git push
